CREATE TABLE `spell_lplus` (
  `ID` int NOT NULL DEFAULT '0',
  `Category` int unsigned NOT NULL DEFAULT '0',
  `DispelType` int unsigned NOT NULL DEFAULT '0',
  `Mechanic` int unsigned NOT NULL DEFAULT '0',
  `Attributes` int unsigned NOT NULL DEFAULT '0',
  `AttributesEx` int unsigned NOT NULL DEFAULT '0',
  `AttributesExB` int unsigned NOT NULL DEFAULT '0',
  `AttributesExC` int unsigned NOT NULL DEFAULT '0',
  `AttributesExD` int unsigned NOT NULL DEFAULT '0',
  `AttributesExE` int unsigned NOT NULL DEFAULT '0',
  `AttributesExF` int unsigned NOT NULL DEFAULT '0',
  `AttributesExG` int unsigned NOT NULL DEFAULT '0',
  `ShapeshiftMask` bigint unsigned NOT NULL DEFAULT '0',
  `ShapeshiftExclude` bigint unsigned NOT NULL DEFAULT '0',
  `Targets` int unsigned NOT NULL DEFAULT '0',
  `TargetCreatureType` int unsigned NOT NULL DEFAULT '0',
  `RequiresSpellFocus` int unsigned NOT NULL DEFAULT '0',
  `FacingCasterFlags` int unsigned NOT NULL DEFAULT '0',
  `CasterAuraState` int unsigned NOT NULL DEFAULT '0',
  `TargetAuraState` int unsigned NOT NULL DEFAULT '0',
  `ExcludeCasterAuraState` int unsigned NOT NULL DEFAULT '0',
  `ExcludeTargetAuraState` int unsigned NOT NULL DEFAULT '0',
  `CasterAuraSpell` int unsigned NOT NULL DEFAULT '0',
  `TargetAuraSpell` int unsigned NOT NULL DEFAULT '0',
  `ExcludeCasterAuraSpell` int unsigned NOT NULL DEFAULT '0',
  `ExcludeTargetAuraSpell` int unsigned NOT NULL DEFAULT '0',
  `CastingTimeIndex` int unsigned NOT NULL DEFAULT '0',
  `RecoveryTime` int unsigned NOT NULL DEFAULT '0',
  `CategoryRecoveryTime` int unsigned NOT NULL DEFAULT '0',
  `InterruptFlags` int unsigned NOT NULL DEFAULT '0',
  `AuraInterruptFlags` int unsigned NOT NULL DEFAULT '0',
  `ChannelInterruptFlags` int unsigned NOT NULL DEFAULT '0',
  `ProcTypeMask` int unsigned NOT NULL DEFAULT '0',
  `ProcChance` int unsigned NOT NULL DEFAULT '0',
  `ProcCharges` int unsigned NOT NULL DEFAULT '0',
  `MaxLevel` int unsigned NOT NULL DEFAULT '0',
  `BaseLevel` int unsigned NOT NULL DEFAULT '0',
  `SpellLevel` int unsigned NOT NULL DEFAULT '0',
  `DurationIndex` int unsigned NOT NULL DEFAULT '0',
  `PowerType` int NOT NULL DEFAULT '0',
  `ManaCost` int unsigned NOT NULL DEFAULT '0',
  `ManaCostPerLevel` int unsigned NOT NULL DEFAULT '0',
  `ManaPerSecond` int unsigned NOT NULL DEFAULT '0',
  `ManaPerSecondPerLevel` int unsigned NOT NULL DEFAULT '0',
  `RangeIndex` int unsigned NOT NULL DEFAULT '0',
  `Speed` float NOT NULL DEFAULT '0',
  `ModalNextSpell` int unsigned NOT NULL DEFAULT '0',
  `CumulativeAura` int unsigned NOT NULL DEFAULT '0',
  `Totem_1` int unsigned NOT NULL DEFAULT '0',
  `Totem_2` int unsigned NOT NULL DEFAULT '0',
  `Reagent_1` int NOT NULL DEFAULT '0',
  `Reagent_2` int NOT NULL DEFAULT '0',
  `Reagent_3` int NOT NULL DEFAULT '0',
  `Reagent_4` int NOT NULL DEFAULT '0',
  `Reagent_5` int NOT NULL DEFAULT '0',
  `Reagent_6` int NOT NULL DEFAULT '0',
  `Reagent_7` int NOT NULL DEFAULT '0',
  `Reagent_8` int NOT NULL DEFAULT '0',
  `ReagentCount_1` int NOT NULL DEFAULT '0',
  `ReagentCount_2` int NOT NULL DEFAULT '0',
  `ReagentCount_3` int NOT NULL DEFAULT '0',
  `ReagentCount_4` int NOT NULL DEFAULT '0',
  `ReagentCount_5` int NOT NULL DEFAULT '0',
  `ReagentCount_6` int NOT NULL DEFAULT '0',
  `ReagentCount_7` int NOT NULL DEFAULT '0',
  `ReagentCount_8` int NOT NULL DEFAULT '0',
  `EquippedItemClass` int NOT NULL DEFAULT '0',
  `EquippedItemSubclass` int NOT NULL DEFAULT '0',
  `EquippedItemInvTypes` int NOT NULL DEFAULT '0',
  `Effect_1` int unsigned NOT NULL DEFAULT '0',
  `Effect_2` int unsigned NOT NULL DEFAULT '0',
  `Effect_3` int unsigned NOT NULL DEFAULT '0',
  `EffectDieSides_1` int NOT NULL DEFAULT '0',
  `EffectDieSides_2` int NOT NULL DEFAULT '0',
  `EffectDieSides_3` int NOT NULL DEFAULT '0',
  `EffectRealPointsPerLevel_1` float NOT NULL DEFAULT '0',
  `EffectRealPointsPerLevel_2` float NOT NULL DEFAULT '0',
  `EffectRealPointsPerLevel_3` float NOT NULL DEFAULT '0',
  `EffectBasePoints_1` int NOT NULL DEFAULT '0',
  `EffectBasePoints_2` int NOT NULL DEFAULT '0',
  `EffectBasePoints_3` int NOT NULL DEFAULT '0',
  `EffectMechanic_1` int unsigned NOT NULL DEFAULT '0',
  `EffectMechanic_2` int unsigned NOT NULL DEFAULT '0',
  `EffectMechanic_3` int unsigned NOT NULL DEFAULT '0',
  `ImplicitTargetA_1` int unsigned NOT NULL DEFAULT '0',
  `ImplicitTargetA_2` int unsigned NOT NULL DEFAULT '0',
  `ImplicitTargetA_3` int unsigned NOT NULL DEFAULT '0',
  `ImplicitTargetB_1` int unsigned NOT NULL DEFAULT '0',
  `ImplicitTargetB_2` int unsigned NOT NULL DEFAULT '0',
  `ImplicitTargetB_3` int unsigned NOT NULL DEFAULT '0',
  `EffectRadiusIndex_1` int unsigned NOT NULL DEFAULT '0',
  `EffectRadiusIndex_2` int unsigned NOT NULL DEFAULT '0',
  `EffectRadiusIndex_3` int unsigned NOT NULL DEFAULT '0',
  `EffectAura_1` int unsigned NOT NULL DEFAULT '0',
  `EffectAura_2` int unsigned NOT NULL DEFAULT '0',
  `EffectAura_3` int unsigned NOT NULL DEFAULT '0',
  `EffectAuraPeriod_1` int unsigned NOT NULL DEFAULT '0',
  `EffectAuraPeriod_2` int unsigned NOT NULL DEFAULT '0',
  `EffectAuraPeriod_3` int unsigned NOT NULL DEFAULT '0',
  `EffectMultipleValue_1` float NOT NULL DEFAULT '0',
  `EffectMultipleValue_2` float NOT NULL DEFAULT '0',
  `EffectMultipleValue_3` float NOT NULL DEFAULT '0',
  `EffectChainTargets_1` int unsigned NOT NULL DEFAULT '0',
  `EffectChainTargets_2` int unsigned NOT NULL DEFAULT '0',
  `EffectChainTargets_3` int unsigned NOT NULL DEFAULT '0',
  `EffectItemType_1` int unsigned NOT NULL DEFAULT '0',
  `EffectItemType_2` int unsigned NOT NULL DEFAULT '0',
  `EffectItemType_3` int unsigned NOT NULL DEFAULT '0',
  `EffectMiscValue_1` int NOT NULL DEFAULT '0',
  `EffectMiscValue_2` int NOT NULL DEFAULT '0',
  `EffectMiscValue_3` int NOT NULL DEFAULT '0',
  `EffectMiscValueB_1` int NOT NULL DEFAULT '0',
  `EffectMiscValueB_2` int NOT NULL DEFAULT '0',
  `EffectMiscValueB_3` int NOT NULL DEFAULT '0',
  `EffectTriggerSpell_1` int unsigned NOT NULL DEFAULT '0',
  `EffectTriggerSpell_2` int unsigned NOT NULL DEFAULT '0',
  `EffectTriggerSpell_3` int unsigned NOT NULL DEFAULT '0',
  `EffectPointsPerCombo_1` float NOT NULL DEFAULT '0',
  `EffectPointsPerCombo_2` float NOT NULL DEFAULT '0',
  `EffectPointsPerCombo_3` float NOT NULL DEFAULT '0',
  `EffectSpellClassMaskA_1` int unsigned NOT NULL DEFAULT '0',
  `EffectSpellClassMaskA_2` int unsigned NOT NULL DEFAULT '0',
  `EffectSpellClassMaskA_3` int unsigned NOT NULL DEFAULT '0',
  `EffectSpellClassMaskB_1` int unsigned NOT NULL DEFAULT '0',
  `EffectSpellClassMaskB_2` int unsigned NOT NULL DEFAULT '0',
  `EffectSpellClassMaskB_3` int unsigned NOT NULL DEFAULT '0',
  `EffectSpellClassMaskC_1` int unsigned NOT NULL DEFAULT '0',
  `EffectSpellClassMaskC_2` int unsigned NOT NULL DEFAULT '0',
  `EffectSpellClassMaskC_3` int unsigned NOT NULL DEFAULT '0',
  `SpellVisualID_1` int unsigned NOT NULL DEFAULT '0',
  `SpellVisualID_2` int unsigned NOT NULL DEFAULT '0',
  `SpellIconID` int unsigned NOT NULL DEFAULT '0',
  `ActiveIconID` int unsigned NOT NULL DEFAULT '0',
  `SpellPriority` int unsigned NOT NULL DEFAULT '0',
  `Name_Lang_enUS` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci,
  `Name_Lang_enGB` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci,
  `Name_Lang_koKR` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci,
  `Name_Lang_frFR` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci,
  `Name_Lang_deDE` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci,
  `Name_Lang_enCN` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci,
  `Name_Lang_zhCN` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci,
  `Name_Lang_enTW` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci,
  `Name_Lang_zhTW` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci,
  `Name_Lang_esES` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci,
  `Name_Lang_esMX` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci,
  `Name_Lang_ruRU` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci,
  `Name_Lang_ptPT` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci,
  `Name_Lang_ptBR` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci,
  `Name_Lang_itIT` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci,
  `Name_Lang_Unk` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci,
  `Name_Lang_Mask` int unsigned NOT NULL DEFAULT '0',
  `NameSubtext_Lang_enUS` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci,
  `NameSubtext_Lang_enGB` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci,
  `NameSubtext_Lang_koKR` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci,
  `NameSubtext_Lang_frFR` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci,
  `NameSubtext_Lang_deDE` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci,
  `NameSubtext_Lang_enCN` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci,
  `NameSubtext_Lang_zhCN` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci,
  `NameSubtext_Lang_enTW` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci,
  `NameSubtext_Lang_zhTW` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci,
  `NameSubtext_Lang_esES` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci,
  `NameSubtext_Lang_esMX` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci,
  `NameSubtext_Lang_ruRU` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci,
  `NameSubtext_Lang_ptPT` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci,
  `NameSubtext_Lang_ptBR` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci,
  `NameSubtext_Lang_itIT` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci,
  `NameSubtext_Lang_Unk` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci,
  `NameSubtext_Lang_Mask` int unsigned NOT NULL DEFAULT '0',
  `Description_Lang_enUS` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci,
  `Description_Lang_enGB` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci,
  `Description_Lang_koKR` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci,
  `Description_Lang_frFR` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci,
  `Description_Lang_deDE` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci,
  `Description_Lang_enCN` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci,
  `Description_Lang_zhCN` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci,
  `Description_Lang_enTW` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci,
  `Description_Lang_zhTW` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci,
  `Description_Lang_esES` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci,
  `Description_Lang_esMX` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci,
  `Description_Lang_ruRU` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci,
  `Description_Lang_ptPT` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci,
  `Description_Lang_ptBR` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci,
  `Description_Lang_itIT` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci,
  `Description_Lang_Unk` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci,
  `Description_Lang_Mask` int unsigned NOT NULL DEFAULT '0',
  `AuraDescription_Lang_enUS` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci,
  `AuraDescription_Lang_enGB` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci,
  `AuraDescription_Lang_koKR` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci,
  `AuraDescription_Lang_frFR` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci,
  `AuraDescription_Lang_deDE` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci,
  `AuraDescription_Lang_enCN` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci,
  `AuraDescription_Lang_zhCN` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci,
  `AuraDescription_Lang_enTW` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci,
  `AuraDescription_Lang_zhTW` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci,
  `AuraDescription_Lang_esES` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci,
  `AuraDescription_Lang_esMX` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci,
  `AuraDescription_Lang_ruRU` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci,
  `AuraDescription_Lang_ptPT` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci,
  `AuraDescription_Lang_ptBR` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci,
  `AuraDescription_Lang_itIT` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci,
  `AuraDescription_Lang_Unk` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci,
  `AuraDescription_Lang_Mask` int unsigned NOT NULL DEFAULT '0',
  `ManaCostPct` int unsigned NOT NULL DEFAULT '0',
  `StartRecoveryCategory` int unsigned NOT NULL DEFAULT '0',
  `StartRecoveryTime` int unsigned NOT NULL DEFAULT '0',
  `MaxTargetLevel` int unsigned NOT NULL DEFAULT '0',
  `SpellClassSet` int unsigned NOT NULL DEFAULT '0',
  `SpellClassMask_1` int unsigned NOT NULL DEFAULT '0',
  `SpellClassMask_2` int unsigned NOT NULL DEFAULT '0',
  `SpellClassMask_3` int unsigned NOT NULL DEFAULT '0',
  `MaxTargets` int unsigned NOT NULL DEFAULT '0',
  `DefenseType` int unsigned NOT NULL DEFAULT '0',
  `PreventionType` int unsigned NOT NULL DEFAULT '0',
  `StanceBarOrder` int unsigned NOT NULL DEFAULT '0',
  `EffectChainAmplitude_1` float NOT NULL DEFAULT '0',
  `EffectChainAmplitude_2` float NOT NULL DEFAULT '0',
  `EffectChainAmplitude_3` float NOT NULL DEFAULT '0',
  `MinFactionID` int unsigned NOT NULL DEFAULT '0',
  `MinReputation` int unsigned NOT NULL DEFAULT '0',
  `RequiredAuraVision` int unsigned NOT NULL DEFAULT '0',
  `RequiredTotemCategoryID_1` int unsigned NOT NULL DEFAULT '0',
  `RequiredTotemCategoryID_2` int unsigned NOT NULL DEFAULT '0',
  `RequiredAreasID` int NOT NULL DEFAULT '0',
  `SchoolMask` int unsigned NOT NULL DEFAULT '0',
  `RuneCostID` int unsigned NOT NULL DEFAULT '0',
  `SpellMissileID` int unsigned NOT NULL DEFAULT '0',
  `PowerDisplayID` int NOT NULL DEFAULT '0',
  `Field227` float NOT NULL DEFAULT '0',
  `Field228` float NOT NULL DEFAULT '0',
  `Field229` float NOT NULL DEFAULT '0',
  `SpellDescriptionVariableID` int unsigned NOT NULL DEFAULT '0',
  `SpellDifficultyID` int unsigned NOT NULL DEFAULT '0',
  PRIMARY KEY (`ID`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
